version: '3.7'

services:
  db:
    image: postgres
    container_name: friends-net-db
    volumes:
      - friends-net-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=superstrongpassword
      - PGDATA=/var/lib/postgresql/data/friends-net-data
      - POSTGRES_DB=friends-net-db
    shm_size: 256MB

# docker run --name friends-net-db -e POSTGRES_PASSWORD=superstrongpassword -e POSTGRES_USER=root -e PGDATA=/var/lib/postgresql/data/friends-net-data -e POSTGRES_DB=friends-net-db -d --shm-size=256MB -p5432:5432 -v friends-net-data:/var/lib/postgresql/data postgres
