logging:
  level:
    cz: DEBUG
    org:
      apache: WARN
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    #          context:
    #            support:
    #              SpringBeanAutowiringSupport: ERROR
    com: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/friends-net-db
    username: root
    password: superstrongpassword

jwt:
  secret: kiv/pia