logging:
  level:
    com: INFO
    cz: INFO
    org: INFO

spring:
  datasource:
    url: jdbc:postgresql://friends-net-db:5432/friends-net-db
    username: root
    password: superstrongpassword

jwt:
  secret: kiv/pia