logging:
  level:
#    root: DEBUG
    org:
      apache: WARN
#      springframework:
#        web:
#          context:
#            support:
#              SpringBeanAutowiringSupport: ERROR
    com: INFO

jwt:
  secret: kiv/pia

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/friends-net-db
    username: root
    password: superstrongpassword